### PR TITLE
Remove manual image build

### PR DESCRIPTION
**Pull request by itskingori**
Since we have set up automated builds on master and tags.

### CODE REVIEW

**Review by zacblazic — APPROVED** [review]
Not sure if this will be better or worse, but its worth testing out!

**Comment by itskingori** [comment]
It is better. 😁 Because ... when you set a repo this way you get many more options.

screen shot 2016-09-16 at 16 05 36

That is:
- The `latest` tag
- The Dockerfile link at the top
- Link to the source repo on the right
- Build settings

I’ve configured it to build only master and tags … which would only trigger after CircleCI tests pass (and review).

screen shot 2016-09-16 at 15 54 14

**Comment by zacblazic** [comment]
Hmm, but won’t the Docker Hub Automated Build run in parallel with Circle?

image

**Comment by itskingori** [comment]
I've unchecked the ... _when active, builds will happen automatically on pushes_ ... option. 

screen shot 2016-09-16 at 16 14 16

**Comment by zacblazic** [comment]
So this means we'll need to manually trigger the builds on Docker Hub then?

**Comment by itskingori** [comment]
@zacblazic Honestly, I dunno. I'd presume it would build on merging to master and creation of a tag.

screen shot 2016-09-16 at 16 39 11

**Comment by zacblazic** [comment]
Right, I get your point! Before anything gets into `master` it would have been run through Circle (except for a tag though, that can bypass it).

However, I think we'd need the setting enabled for that to work though - from the wording:

> The build rules below specify how to build your source into Docker images. The name can be a string or a regex.

**Pull request merged**
